web_site/urls.py
from django.urls import re_path, path
from . import views

# Favicon
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [

    re_path(r'^$', views.index, name="index"),

    re_path(r'^WitBot/$', views.witbot, name="witbot"),

    re_path(r'^Game/$', views.game, name="game"),

    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('static/favicon/favicon.ico')))

]
app_name = "website"

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('web_site.urls', namespace='web_site')),
]

web_site/models.py
from typing import Text
from django.db import models

class Topic(models.Model):
    '''
    Bloco dedicado à introdução de assuntos
    '''
    text = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text

class Entry(models.Model):
    '''
    Bloco definido à introdução de texto dos assuntos
    '''
    text = models.TextField()
    entry = models.ForeignKey(Topic, on_delete=models.PROTECT)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name_plural = 'entries'
    def __str__(self):
            return self.text

web_site/views.py
from multiprocessing import context
from django.shortcuts import render
from .models import Topic, Entry

# Create your views here.

def index(request):
    return render(request, 'web_site/index.html')

def topic(request):
    topic = Topic.objects.order_by('date_added')
    context = {'topic':topic}

    return render(request, 'web_site/index.html', context)

def witbot(request):
    topic = Topic.objects.order_by('date_added')
    context={'topic':topic}

    return render(request, 'web_site/witbot.html', context)

def game(request):
    topic = Topic.objects.order_by('date_added')
    context = {'topic':topic}

    return render(request, 'web_site/game.html', context)

web_site/templates/web_site/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <title>Nícolas Auervalt</title>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src='main.js'></script>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}"/>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
        <link rel="mask-icon" href="% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
    </head>

    <div class='container'>

        <body>
            <!-- NavBar -->
            <div class="mx-auto" style="width: 200px;"></div>
            <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'web_site:index'%}">Nícolas' Website</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web_site:witbot'%}">WitBot</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web_site:game'%}">Game</a>
                            </li>
                        </ul>
                    </div>
                </div>
    </div>
    </nav>
    </div>
    {%block content%}
    {%endblock content%}
    </body>

</html>

web_site/templates/web_site/game.html
{%extends 'web_site/base.html'%}
{%load static%}

<!DOCTYPE html>
<html>

  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Alien Game</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
  </head>

  <body>
    {%block content%}
    <div class="container">
      <center>
        <br>
        <div class="container fs-2 mt-5">
          <p class="text-center"> Alien Game </p>
        </div>

        <div class="card" style="width: 40rem;">
          <img src="{%static 'images/bg1.png'%}" class="card-img" alt="...">
          <div class="card-body">
            <h5 class="card-title">Sobre</h5>
            <p class="card-text">Esse é um projeto experimental de um jogo em que Alien estão tentando eliminar
              a humanidade da terra, e seu objetivo é derrotar a maior quantidade de alienígenas possível. O jogo
              se passa no espaço, o jogador controla diferentes naves que contam com características únicas.
            </p>
            <img src="{%static 'images/nave.png'%}" alt="...">
            <p class="card-text"><br></div>
            <p class="card-text">Por enquanto, o jogo está em desenvolvimento, possívelmente estará disponível
              entre dezembro e fevereiro.
            <p>
              <p class="card-text">Link de Download (Em Breve)</p>
              <a class="card-text" href="https://www.instagram.com/nic.auersvalt/?fbclid=IwAR3LJJ8xl_Kd5FFOT_BQqM3hkuZslO-11zcxYUJgPLsy7uYtzO8pKEIP9qw">Instagram de Projetos</a>
            <p class="card-text"><small class="text-muted">Versão 1.1</small></p>
          </div>


      </center>
    </div>
    {%endblock content%}
  </body>

</html>

web_site/templates/web_site/index.html
{%extends 'web_site/base.html'%}
{%load static%}

<!DOCTYPE html>
<html>

  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>

    
  </head>

  <body>
    {%block content%}

    <div class="container">
      <p class="text-center"> .</p>
    </div>

    <div class="container fs-2 mt-5">
      <p class="text-center"> Meus Projetos</p>
    </div>

    <div class="container">

      <div class="card-group mt-3">
        <div class="card">
          <img src="{%static 'images/robo3.png'%}" class="card-img-top" alt="...">
          <div class="card-body">
            <center>
              <h5 class="card-title">WitBot</h5>
              <p class="card-text">Uma Plataforma Robótica com Braço Robótico, sensor ultrassônico,
                ESP8266, Motor Shield. Possui Chassi 4w, Braço giratório em até 180°.
                Código desenvolvido em C++ para Arduino Uno R3</p>
          </div>
          <a href="{% url 'web_site:witbot'%}" class="btn btn-primary">Ler</a>
          <div class="card-footer">
            <small class="text-muted">Versão 1.1</small>
            </center>
          </div>
        </div>
        <div class="card">
          <img src="{%static 'images/bg1.png'%}" class="card-img-top" alt="...">
          <div class="card-body">
            <center>
              <h5 class="card-title">Alien Game</h5>
              <p class="card-text">Esse é um jogo de nave contra aliens. O mundo está tomado por Aliens e você precisa
                eliminá-los antes do eclipse, caso contrário, haverá um extermínio em massa dos humanos.</p>
          </div>
          <a href="{% url 'web_site:game'%}" class="btn btn-primary">Ler</a>
          <div class="card-footer">
            <small class="text-muted">Versão 1.0</small>
            </center>
          </div>
        </div>
      </div>

      {%endblock content%}
  </body>

</html>

web_site/templates/web_site/witbot.html
{%extends 'web_site/base.html'%}
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html>

  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>WitBot</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
  </head>

  <body>
    {%block content%}
    <div class="container">
      <center>
        <br>
        <div class="container fs-2 mt-5">
          <p class="text-center"> WitBot</p>
        </div>

        <div class="card" style="width: 40rem;">
          <img src="{%static 'images/robo3.png'%}" class="card-img" alt="...">
          <div class="card-body">
            <h5 class="card-title">Geral</h5>
            <p class="card-text">Esse é o WitBot, um projeto de chassi robótico controlado pelo aplicativo Blynk e
              conta com um braço robótico. Além disso, entre seus componentes se destacam:
              Motor Shield L293D; ESP8266; 4 Pilhas 1.2v e 1 Pilha 9v, Arduino Uno R3. Entretanto, sua versão 1.1
              não conta com as funcionalidades do braço, mas as versões futuras vão trazer.
            </p>
            <p class="card-text"><small class="text-muted">Versão 1.1</small></p>
          </div>
        </div>

        <div class="card" style="width: 40rem;">
          <img src="{%static 'images/robo2.png'%}" class="card-img" alt="...">
          <div class="card-body">
            <h5 class="card-title">Funcionalidades</h5>
            <p class="card-text">Separamos suas funcionalidades em duas partes, chassi e braço.
            <p class="card-text">Chassi: Movimentação frontal ou retrógrada, acelerada ou retardada, e curvas ou repouso. Sua aceleração é determinada pelo deslocamento do Joystick no Blynk,
            se caso não houver deslocamento, então haverá repouso.</p>
            <p class="card-text">Braço: Giro em até 180° sobre sua base, extensão e retração do braço,
               abertura e fechamento da garra. O giro sobre a base é determinado pelo deslocamento no eixo x
              do Joystick, enquanto que sua extensão braçal é pelo eixo y, e a garra pelo pressionamento do botão.</p>
            </p>
            <p class="card-text"><small class="text-muted">Versão 1.1</small></p>
          </div>
        </div>

        <div class="card" style="width: 40rem;">
          <img src="{%static 'images/robo.png'%}" class="card-img" alt="...">
          <div class="card-body">
            <h5 class="card-title">Futuro</h5>
            <p class="card-text">Na versão 1.0, o WitBot era composto apenas do chassi, mas tinha características
              únicas como garra robótica, sensor ultrassônico e led. O led acendia conforme a abertura da garra fosse acionada e
              o sensor limitava o movimento do chassi próximo a qualquer obstáculos.
            </p>
            <p class="card-text">No futuro, haverão as funcionalidades da versão 1.1, com exceção da garra.</p>
            <a class="card-text" href="https://github.com/NicolasAuersvalt/projects/tree/main/cpp/WitBot?fbclid=IwAR3f85hEK2-6QIvUeqnxaqjCSbc4u-z2Sk9kAlkD9sOZOTRxmfZlwslDyZw">Repositório do Projeto</a>
            <p class="card-text"><p>
            <a class="card-text" href="https://www.instagram.com/nic.auersvalt/?fbclid=IwAR3LJJ8xl_Kd5FFOT_BQqM3hkuZslO-11zcxYUJgPLsy7uYtzO8pKEIP9qw">Instagram de Projetos</a>

            <p class="card-text"><small class="text-muted">Version 1.0</small></p>
          </div>
        </div>
      </center>
    </div>
    {%endblock content%}
  </body>

</html>